name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # we have already installed everything
          install: false
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct
