name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run lint and component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          command: yarn ci
